services:
  rabbitmq:
    image: ${RMQ_IMAGE:?}
    container_name: rabbitmq
    restart: unless-stopped
    network_mode: host
    environment:
      RABBITMQ_NODENAME: ${RMQ_NODENAME:?}
      RABBITMQ_USE_LONGNAME: "true"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/20-red5pro.conf:ro
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "5"
